### ISSUE TITLE
getRealPath never resolve on ios

### ISSUE THREAD

**Issue by deflexable** [Shobbak/react-native-compressor#128]
```js
import { getRealPath } from 'react-native-compressor';

const realPath = await getRealPath(fileUri, 'video'); //   file://file_path.extension
```

getRealPath function neither convert "content://" nor "ph://" to "file://" on both ios and android

**Comment by deflexable** [comment]
discovered, i was calling the method in a wrong was.
i changed this:
```js
const realPath = await getRealPath(fileUri);
```

to this:

```js
const realPath = await getRealPath(fileUri);
```

and it works fine

**Comment by dingtwo** [comment]
> discovered, i was calling the method in a wrong was. i changed this:
> 
> ```js
> const realPath = await getRealPath(fileUri);
> ```
> 
> to this:
> 
> ```js
> const realPath = await getRealPath(fileUri);
> ```
> 
> and it works fine

What is the difference between these two lines of code? I compared them using 'diff' and they appear to be the same.
