### ISSUE TITLE
maxSize isn't implemented for manual compression (iOS)

### ISSUE THREAD

**Issue by closetothe** [Shobbak/react-native-compressor#130]
### Current behavior
The `maxSize` is always 1920 when the compressionMode is `manual`. See `manualCompressionHelper` inside `VideoCompressor.swift` – it's hardcoded to 1920
### Expected behavior
`maxSize` is set from the given options and 1920 is used as a fallback.
### Platform

- [?] Android (dont know)
- [X] iOS

### React Native Version
0.68.2
### React Native Compressor Version
1.6.1
### Reproducible Steps And Demo
Try setting the maxSize with `compressionMethod: "manual"` – but there's no point in reproducing it, you can see right there in the code that it's always set to 1920

**Comment by numandev1** [comment]
released in `1.7.0`
