### ISSUE TITLE
RN 0.65.0 require some new listener methods on the Native Module when call the NativeEventEmitter. It shows the "new NativeEventEmmiter()..." warning.

### ISSUE THREAD

**Issue by DarWiM** [Shobbak/react-native-compressor#132]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-compressor@1.6.1` for the project I'm working on.

A lot of libraries, including this one is showing a warning with the message: "new NativeEventEmitter() was called with a non-null argument without the required addListener/removeListeners method." Like the image below:
![image](https://user-images.githubusercontent.com/2218747/196653840-912a8985-3b9d-455a-9fb8-c438ff0adb5c.png)

This warning is shown because of the commit [114be1d](https://github.com/facebook/react-native/commit/114be1d2170bae2d29da749c07b45acf931e51e2), which checks if the Native Module has the methods: addListener and removeListeners. These checks are necessary because of this commit [f5502fb](https://github.com/facebook/react-native/commit/f5502fbda9fe271ff6e1d0da773a3a8ee206a453), which tries to use the Native Module to notify subscriptions on Android. So I think this issue is only related to Android and the 0.65.0 release.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-compressor/android/src/main/java/com/reactnativecompressor/Video/VideoModule.java b/node_modules/react-native-compressor/android/src/main/java/com/reactnativecompressor/Video/VideoModule.java
index be1ba60..4cb5d4c 100644
--- a/node_modules/react-native-compressor/android/src/main/java/com/reactnativecompressor/Video/VideoModule.java
+++ b/node_modules/react-native-compressor/android/src/main/java/com/reactnativecompressor/Video/VideoModule.java
@@ -110,4 +110,14 @@ public class  VideoModule extends ReactContextBaseJavaModule {
       promise.reject(ex);
     }
   }
+
+  @ReactMethod
+  public void addListener(String eventName) {
+    // Keep: Required for RN built in Event Emitter Calls.
+  }
+
+  @ReactMethod
+  public void removeListeners(Integer count) {
+    // Keep: Required for RN built in Event Emitter Calls.
+  }
 }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by sagar17-create** [comment]
any fix ?

**Comment by cyhnkckali** [comment]
I would be very happy if this issue is corrected.

**Comment by aricab** [comment]
Same problem with RN 0.69.5.

**Comment by ronal2s** [comment]
Same issue with 0.71.2

**Comment by luizaugustoventura** [comment]
> Hi! wave
> 
> Firstly, thanks for your work on this project! slightly_smiling_face
> 
> Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-compressor@1.6.1` for the project I'm working on.
> 
> A lot of libraries, including this one is showing a warning with the message: "new NativeEventEmitter() was called with a non-null argument without the required addListener/removeListeners method." Like the image below: ![image](https://user-images.githubusercontent.com/2218747/196653840-912a8985-3b9d-455a-9fb8-c438ff0adb5c.png)
> 
> This warning is shown because of the commit [114be1d](https://github.com/facebook/react-native/commit/114be1d2170bae2d29da749c07b45acf931e51e2), which checks if the Native Module has the methods: addListener and removeListeners. These checks are necessary because of this commit [f5502fb](https://github.com/facebook/react-native/commit/f5502fbda9fe271ff6e1d0da773a3a8ee206a453), which tries to use the Native Module to notify subscriptions on Android. So I think this issue is only related to Android and the 0.65.0 release.
> 
> Here is the diff that solved my problem:
> 
> ```diff
> diff --git a/node_modules/react-native-compressor/android/src/main/java/com/reactnativecompressor/Video/VideoModule.java b/node_modules/react-native-compressor/android/src/main/java/com/reactnativecompressor/Video/VideoModule.java
> index be1ba60..4cb5d4c 100644
> --- a/node_modules/react-native-compressor/android/src/main/java/com/reactnativecompressor/Video/VideoModule.java
> +++ b/node_modules/react-native-compressor/android/src/main/java/com/reactnativecompressor/Video/VideoModule.java
> @@ -110,4 +110,14 @@ public class  VideoModule extends ReactContextBaseJavaModule {
>        promise.reject(ex);
>      }
>    }
> +
> +  @ReactMethod
> +  public void addListener(String eventName) {
> +    // Keep: Required for RN built in Event Emitter Calls.
> +  }
> +
> +  @ReactMethod
> +  public void removeListeners(Integer count) {
> +    // Keep: Required for RN built in Event Emitter Calls.
> +  }
>  }
> ```
> 
> _This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296)._

I was trying to compress an image using the `Image.compress(imagePath, { compressionMethod: 'auto' })` method and got those warnings.

Trying your solution worked well for me. But as no one took action about it, I decided to create a PR (#149) with your changes.

Thank you soo much for sharing this fix.
