### ISSUE TITLE
Getting error while image compression.

### ISSUE THREAD

**Issue by krupalikevadiya** [Shobbak/react-native-compressor#19]
Please check below attached screenshot for more details and also i added my code.

 Image.compress(path, {
          maxWidth:width,
          maxHeight:.height,
          input: 'uri',
          output: 'jpg',
          quality: 0.5,
          returnableOutputType: 'uri',
        })
          .then(async (compressedFileUri) => {
            console.log('===========image compressed=============' + JSON.stringify(detail, null, 2))
  
            const detail = await getFileInfo(compressedFileUri);
          })
          .catch((e) => {
            console.log( '==============error in compression===================');
          });

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-06-23 at 18 08 02](https://user-images.githubusercontent.com/69295445/123099590-f4d47000-d44f-11eb-96b3-9ca01f1740e3.png)

**Comment by nomi9995** [comment]
@krupalikevadiya did you install `react-native-fs` ?

**Comment by krupalikevadiya** [comment]
No there is no any description to add react-native-fs in Readme. Anyway let me check by adding it.

**Comment by nomi9995** [comment]
@krupalikevadiya this package is in progress. I will add a description or remove fs in the future.

**Comment by nomi9995** [comment]
@krupalikevadiya fixed in `0.5.1`

**Comment by krupalikevadiya** [comment]
Okk it is worked for image compression but does not for video compression.It gives same size of video after compression.

**Comment by nomi9995** [comment]
@krupalikevadiya with `compressionMethod: 'auto'` you can achieve compression-like **Whatsapp** and **Whatsapp** cannot compress video have less than equal to 16MB. i will add this description in the readme so users know why we are not compressing below 16MB video in auto mode

if you wanna compress video which is below `16MB` then you can use `compressionMethod:'manual'` prop

**Comment by krupalikevadiya** [comment]
Yes i used this props but did not get compressed video. Here is my code.
  const result = await Video.compress(
      path,
      {
        compressionMethod:'manual',
        bitrate:10,
      },
      (progress) => {
       
      }
    );

Also here result is origional video url not compressed one.

**Comment by nomi9995** [comment]
can you upload video and share link here so i can test it on my side

**Comment by krupalikevadiya** [comment]
link is : https://testing.youchampapp.com/upload/aws/files/redirect/vVzlmU.1625561223284.camera.MP4

**Comment by krupalikevadiya** [comment]
Link : https://drive.google.com/file/d/1VETAcKtngebymwXxQyYuZcaxVOzGGJ0V/view?usp=sharing

**Comment by krupalikevadiya** [comment]
@nomi9995 any update on it?

**Comment by nomi9995** [comment]
@krupalikevadiya I will check it when I am at the home. I will let you know after 5 hour

**Comment by krupalikevadiya** [comment]
okay thanks for quick reply.

**Comment by nomi9995** [comment]
@krupalikevadiya we are using [NextLevelSessionExporter](https://github.com/Shobbak/react-native-compressor/blob/dd5c106522461005acd89d6f679c0ef2f96fdd74/ios/Video/VideoCompressor.swift#L4) pod  for compression videos on ios. but on this video, it is giving an exception, therefore, I am returning the same URI. I have created issue on 
https://github.com/NextLevel/NextLevelSessionExporter/issues/37
we have to wait for resolve issue from `NextLevelSessionExporter` size

**Comment by nomi9995** [comment]
@krupalikevadiya we are using [NextLevelSessionExporter](https://github.com/Shobbak/react-native-compressor/blob/dd5c106522461005acd89d6f679c0ef2f96fdd74/ios/Video/VideoCompressor.swift#L4) pod  for compression videos on ios. but on this video, it is giving an exception, therefore, I am returning the same URI. I have created issue on 
https://github.com/NextLevel/NextLevelSessionExporter/issues/37
we have to wait for resolve issue from `NextLevelSessionExporter` size

**Comment by krupalikevadiya** [comment]
okk thanks and let me know once it is resolved...same thing happen in android to.

**Comment by nomi9995** [comment]
@krupalikevadiya sure. can you send me a reproducible example for android?

**Comment by krupalikevadiya** [comment]
ImagePicker.openPicker({
      multiple: false,
      mediaType: "video",
      cropping: false
    }).then(images => {
      console.log('===========image browsed=============' + JSON.stringify(images, null, 2))

      this.compress_video(images.path,images.width)
      })
      
      async compress_video(path, width) {
    const result = await Video.compress(
      path,
      {
        compressionMethod: 'manual',
        bitrate:10
      },
      (progress) => {

      }
    );
    console.log('=============video compressed=============' + JSON.stringify(result, null, 2))
  }
      
And error is : https://prnt.sc/197jr8u

**Comment by nomi9995** [comment]
@krupalikevadiya can you try `compressionMethod: 'auto'` or remove `bitrate:10`?

**Comment by krupalikevadiya** [comment]
Hey @nomi9995 it is worked with compressionMethod: 'auto' in android but does not work with compressionMethod: 'manual'

**Comment by nomi9995** [comment]
@krupalikevadiya I think we cannot set bitrate:16. can you try with bitrate 450000

**Comment by krupalikevadiya** [comment]
Getting same error of asynctask with following options i tried both bitrate:16 and bitrate:450000.
{
        compressionMethod: 'manual',
        bitrate:16
      },

**Comment by nomi9995** [comment]
@krupalikevadiya  can you add video link here?

**Comment by krupalikevadiya** [comment]
With same video which i use in ios.

**Comment by krupalikevadiya** [comment]
@nomi9995 any update on it? ..i need this package to compress video.
