### ISSUE TITLE
IOS 14 compressed url is not exist

### ISSUE THREAD

**Issue by kerm1it** [Shobbak/react-native-compressor#24]
After compressing photo, the result url is not exist.

This is log:

WARN  Could not find image file://private/var/mobile/Containers/Data/Application/9AD81D94-BF91-4398-BC1D-280B5C864A9B/tmp/98F1A7FE-F2AA-41E7-859B-86AFE1D6E392.jpg

**Comment by nomi9995** [comment]
@kerm1it can you send the me image which you are compression

**Comment by kerm1it** [comment]
It is my error.
