### ISSUE TITLE
[Android] Throw error while compressing image

### ISSUE THREAD

**Issue by kerm1it** [Shobbak/react-native-compressor#25]
When compressing image with path follow: `content://media/external/images/media/78550`

It throw a error:  `[Error: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference]`

It look like `content://media/external/images/media/78550` is not identified.

**Comment by nomi9995** [comment]
@kerm1it we need the absolute path, if you wanna fix this issue then you can do like this for android

```
import RNFS from 'react-native-fs';

const destPath = `${RNFS.TemporaryDirectoryPath}/${shortid.generate()}`;
await RNFS.copyFile(selectedDocument.uri, destPath);
```

then you can send deskPath for compression

ref: https://github.com/itinance/react-native-fs/pull/395

**Comment by kerm1it** [comment]
Thanks.
