### ISSUE TITLE
Video not compressing below 10 mb

### ISSUE THREAD

**Issue by aamez** [Shobbak/react-native-compressor#26]
Hi, first of all I appreciate your effort for making this package. Gone through your excel for video compress, can you do the compression for video below 10 mb? or else can you refer some other package for the same?

**Comment by nomi9995** [comment]
@aamez you can remove this condition for **android**
https://github.com/Shobbak/react-native-compressor/blob/dd5c106522461005acd89d6f679c0ef2f96fdd74/android/src/main/java/com/reactnativecompressor/Video/AutoVideoCompression/AutoVideoCompression.java#L38

and remove this condition for **IOS** to compress video which size is 16MB
https://github.com/Shobbak/react-native-compressor/blob/dd5c106522461005acd89d6f679c0ef2f96fdd74/ios/Video/VideoCompressor.swift#L205

**Comment by aamez** [comment]
> @aamez you can remove this condition for **android**
> https://github.com/Shobbak/react-native-compressor/blob/dd5c106522461005acd89d6f679c0ef2f96fdd74/android/src/main/java/com/reactnativecompressor/Video/AutoVideoCompression/AutoVideoCompression.java#L38
> 
> and remove this condition for **IOS** to compress video which size is 16MB
> https://github.com/Shobbak/react-native-compressor/blob/dd5c106522461005acd89d6f679c0ef2f96fdd74/ios/Video/VideoCompressor.swift#L205

Great man it worked, thanks :)

**Comment by nomi9995** [comment]
@aamez i will add prop for this

**Comment by aamez** [comment]
> @aamez i will add prop for this

sure thanks... :)

**Comment by aamez** [comment]
> @aamez i will add prop for this

sure thanks @nomi9995 :)

**Comment by joxw1** [comment]
@nomi9995 Was this prop added? Any updates on it?

**Comment by nomi9995** [comment]
@joxw1 no, I did not add. I forgot. i will add it today

**Comment by nomi9995** [comment]
@joxw1 i have added `minimumFileSizeForCompress` for this purpose 

https://github.com/Shobbak/react-native-compressor#minimumfilesizeforcompress-number-default-16

i will release today after fixing one or two more issue

**Comment by joxw1** [comment]
@nomi9995 Thanks! Great effort! 🎉

**Comment by nomi9995** [comment]
https://github.com/Shobbak/react-native-compressor#minimumfilesizeforcompress-number-default-16

just released `1.1.0` version of the compressor which has fixed this issue.

```
yarn add react-native-compressor@1.1.0
```
