### ISSUE TITLE
unable to find compressed image file location on my android emulator.

### ISSUE THREAD

**Issue by rnqayush** [Shobbak/react-native-compressor#27]
1-i went through the installation process and successfully installed the package and compressed my image.
2-After compression i am getting the response uri :  file:///data/user/0/com.mob.innerdots/cache/b45c035e-155e-4b05-8c1e-908cd338fad3.jpg

my issue:
i am not able to get to this uri location in my android emulator. i want to check the properties of compressed image and export it to other file location.

kindly suggest some idea to get this image.

**Comment by nomi9995** [comment]
@rnqayush you can use `Device File Explorer` from android studio to export that file from the android emulator. you will find these compressed files in the tmp folder
![image](https://user-images.githubusercontent.com/36044436/130559390-cf800395-296a-4f24-b00d-a5ae7462b899.png)

**Comment by devashishsharma97** [comment]
<img width="778" alt="Screenshot 2024-12-09 at 4 25 23 PM" src="https://github.com/user-attachments/assets/1ca5d84f-0984-47d8-a519-180bdf2e18ce">

compressed file Path: file:///data/user/0/com.msil.rsa.development/files/recording.mp3
not able to find the compress file anywhere
