### ISSUE TITLE
[Unhandled promise rejection: TypeError: null is not an object (evaluating 'NativeVideoCompressor.compress')]

### ISSUE THREAD

**Issue by elbouhalimohsin** [Shobbak/react-native-compressor#28]
Hi,
I thank you very much for this library, I tried to use it on an mp4 file after a cam record, but I got this message in the title:
[Unhandled promise rejection: TypeError: null is not an object (evaluating 'NativeVideoCompressor.compress')]

  **my function component** 
  const takeVideo = async () => {

    if(camera){
        const data = await camera.recordAsync({
            quality : Camera.Constants.VideoQuality['16:9'],
            videoBitrate : 2*1000*1000,
            maxDuration : 120,
            maxFileSize : 40*1000*1000,
            mute: false

        })
        setRecord(data.uri);

        console.log(data.uri);
      try{  
        const result = await Video.compress(
         data.uri,
          {
            compressionMethod: 'auto',
          },
          (progress) => {
            
            console.log('Compression Progress Front: ', progress);
            
          }
        );

      } catch (err) {
        console.log('Error:', err);
      }

  }
}

**Comment by elbouhalimohsin** [comment]
In this component I try to compress the resutant file of a camera recording

Here is the code of the component, thanks

import React, { useState, useEffect } from 'react';
import { Text, View, TouchableOpacity, SafeAreaView,Button } from 'react-native';
import { Camera } from 'expo-camera';
import axios from 'axios';
import { Video } from 'react-native-compressor';

export default  function Record() {

    const [hasAudioPermission, setHasAudioPermission] = useState(null);
    const [hasCameraPermission, setHasCameraPermission] =useState(null);
    const [camera, setCamera] = useState(null);
    const [zoom, setZoom] = useState(0);
    const [type, setType] = useState(Camera.Constants.Type.back);
    const [loading, setLoading] = useState('----');
    const [record, setRecord] = useState();
    const [storagev, setStorage] = useState('');

    useEffect(() => {
        (async () => {
            const cameraStatus = await Camera.requestPermissionsAsync();
            setHasCameraPermission(cameraStatus.status === 'granted');
            const audioStatus = await Camera.requestMicrophonePermissionsAsync();
                setHasAudioPermission(audioStatus.status === 'granted');
            })();
            

      }, []);
        const stopVideo = async () => {
            camera.stopRecording();
        } 

  const uploadVideo = async(uriFile, data) => {

  
    let dataToLoad = new FormData();
        dataToLoad.append("data", 'data');
        dataToLoad.append("video", {type : 'vido/mp4', uri:uriFile, name:'video.mp4'});
        var config = {
            onUploadProgress: function(progressEvent) {
              var percentCompleted = Math.round( (progressEvent.loaded * 100) / progressEvent.total );
              setLoading(percentCompleted+ "% "+ Math.round(progressEvent.total/1000000)+'Mo');
              console.log(percentCompleted+ "% "+ Math.round(progressEvent.total/1000000)+'Mo');
            }
          };
            
          axios.post("http://192.168.1.251/put.php", dataToLoad, config)
          .then(function (res) {
              console.log('DONE');
            })
            .catch(function (err) {
                console.log(err);
            });
  }

  const takeVideo = async () => {
 
    if(camera){
        const data = await camera.recordAsync({
            quality : Camera.Constants.VideoQuality['16:9'],
            videoBitrate : 2*1000*1000,
            maxDuration : 120,
            maxFileSize : 40*1000*1000,
            mute: false

        })
        setRecord(data.uri);
        
        console.log(data.uri);


      try{  
        const result = await Video.compress(
          data.uri,
          {
            compressionMethod: 'auto',
          },
          (progress) => {
            
            console.log('Compression Progress Front: ', progress);
            
          }
        );

      } catch (err) {
        console.log('Error:', err);
      }
      //uploadVideo(data.uri, null);
        
      return;



  }
}
  if (!hasAudioPermission || !hasCameraPermission ) {
    return <View />;
  }
  
    if (!hasAudioPermission || !hasCameraPermission) {
    return <Text>No access to camera</Text>;
  }
  const aa =async() =>  await camera.getAvailableVideoCodecsAsync();
  return (
      <SafeAreaView style={{flex: 1,margin: 0}}>
          
          <Camera style={{flex:1}}
                ref={ref => setCamera(ref)}
                type={type}
                ratio={'16:9'}
                zoom={zoom}
                quality={Camera.Constants.VideoQuality['4:3']}
                useCamera2Api={true}

                >
              <View
                  style={{
                      height: '40%',
                      backgroundColor: 'transparent',
                      flexDirection: 'row',
                      bottom:0,
                      position:'absolute'
                  }}>
                    <Text style={{top:10, left:10, position:'absolute', color:'#fff', backgroundColor:'#000', width:200}}>
                      {loading}
                    </Text>
                  <TouchableOpacity
                      style={{
                          //flex: 0.1,
                          alignSelf: 'flex-end',
                          alignItems: 'center',
                          margin:10,
                      }}
                      onPress={() => {
                          setType(
                              type === Camera.Constants.Type.back
                                  ? Camera.Constants.Type.front
                                  : Camera.Constants.Type.back
                          );
                      } }>
                      <Text style={{ fontSize: 18, marginBottom: 10, color: 'white' }}> Flip </Text>
                  </TouchableOpacity>
                  <TouchableOpacity
                      style={{
                          //flex: 0.1,
                          alignSelf: 'flex-end',
                          alignItems: 'center',
                          margin:10,
                      }}
                       >
                  <Button title="Take video" onPress={() =>{  
                    
                    //console.log("Camera",camera);
                  
                    takeVideo()
                  } }/>
                  </TouchableOpacity>

                  <TouchableOpacity
                      style={{
                          //flex: 0.1,
                          alignSelf: 'flex-end',
                          alignItems: 'center',
                          margin:10,
                      }}
                      >
                  <Button title="Stop Video"  onPress={() => stopVideo() }/>
                  </TouchableOpacity>
                  <TouchableOpacity
                      style={{
                          //flex: 0.1,
                          alignSelf: 'flex-end',
                          alignItems: 'center',
                          margin:10,
                      }}
                       >
                  </TouchableOpacity>
              </View>
          </Camera>
 
      </SafeAreaView>
  );
}

**Comment by nomi9995** [comment]
@elbouhalimohsin if you make a git repo for reproducible example that would be great because from copy-paste from here is hard to make reproducible example then fix it

**Comment by elbouhalimohsin** [comment]
Hi,
Here is my git : 
https://github.com/elbouhalimohsin/compress

thank you.

**Comment by nomi9995** [comment]
@elbouhalimohsin are you testing with expo?

**Comment by elbouhalimohsin** [comment]
yes "expo": "~42.0.1"

**Comment by nomi9995** [comment]
@elbouhalimohsin we dont support expo. you can test it on `react-native core`

**Comment by elbouhalimohsin** [comment]
Ok bro ;)  thank you for All
