### ISSUE TITLE
unsupported swift version issue is appearing while building on ios.

### ISSUE THREAD

**Issue by rnqayush** [Shobbak/react-native-compressor#29]
I have used this library for image and video compression it is working on android but i am facing issues with building on ios. 
Sharing screenshots of the errors of ios . Kindly suggest some idea to resolve it.
<img width="295" alt="Screenshot 2021-09-08 at 4 55 59 PM (1)" src="https://user-images.githubusercontent.com/74084740/132643265-644dffb0-9902-421c-8e23-09086d5cc0a0.png">
<img width="512" alt="Screenshot 2021-09-08 at 4 58 02 PM (1)" src="https://user-images.githubusercontent.com/74084740/132643276-1d020ac2-9d68-42ea-bf25-d2b48b612b07.png">

**Comment by nomi9995** [comment]
try this
1. Select project 
2. Select Build SettingTab 
3. Select Swift Compiler language Option

[![enter image description here][1]][1]


  [1]: https://i.stack.imgur.com/zGV9Q.png
