### ISSUE TITLE
Could not find or use auto-linked library 'swiftCoreMIDI' when running iOS

### ISSUE THREAD

**Issue by mobilewd** [Shobbak/react-native-compressor#30]
I use react-native-compressor 0.5.2 for compression video, I got issues when trying to run on iOS.
anyone can solve this?

![image](https://user-images.githubusercontent.com/83465439/132778123-4d683581-a0f8-48b3-b257-bea3077f2443.png)

**Comment by nomi9995** [comment]
@mobilewd you can fix thorough **solution 1** from here: https://stackoverflow.com/a/70099586/8079868
