### ISSUE TITLE
error in compressing video in react native v0.65.1

### ISSUE THREAD

**Issue by rnqayush** [Shobbak/react-native-compressor#31]
1-earlier i was using react native 0.61.5 and used this library for video and image compression. it was working as expected.
2- I have upgraded react native version to 0.65.1 and now image compression is working as expected but in video compression i am having errors.
3- i am sharing the screenshot of my code and error kindly suggest some idea to resolve it.
![toshob3](https://user-images.githubusercontent.com/74084740/133382817-e12ae9d9-57f1-485b-90ad-0dfa2b2bb091.PNG)
![toshob](https://user-images.githubusercontent.com/74084740/133382823-6e63e595-76d0-456a-a088-2fe13994596b.PNG)

**Comment by nomi9995** [comment]
@rnqayush I think this error is not from the compressor package. 
i think it is from https://github.com/uuidjs/uuid#getrandomvalues-not-supported

can you provide reproducible example repo? so I can see it

**Comment by rnqayush** [comment]
@nomi9995  thanks for you response, actually i have tested this after removing this video compressor code then it works fine but after implementing this code i get this error.

**Comment by rnqayush** [comment]
@nomi9995 i made a fresh react native project and then installed this package. unfortunately i am getting error kindly look on it and suggest some idea to resolve it.  also i am sharing the github repo.
GitHub: https://github.com/rnqayush/react-native-video-compressor

snapshot of error:
![toshob2](https://user-images.githubusercontent.com/74084740/133736546-6b73877c-1b1b-4d46-87b4-6913cc813b6a.PNG)

**Comment by nomi9995** [comment]
@rnqayush Actually this is due to jcenter, many libraries which were published on jcenter having this issue. we should have to publish all libraries to mavenCenter. I will create a ticket on `mavenCenter` so our library may not be down
https://developer.android.com/studio/build/jcenter-migration
![image](https://user-images.githubusercontent.com/36044436/133736869-8d54e256-5368-4cbe-8551-ba1b1c48aac6.png)

**Comment by rnqayush** [comment]
@nomi9995 thanks a lot for your response, kindly let us know when it is expected to be updated.

**Comment by nomi9995** [comment]
@rnqayush actually I did not publish the library on mavenCenter before. I am going to make ticket on mavenCenter anthen d that the community will review the ticket and then will publish or reject it. it depends on the community review.

**Comment by rnqayush** [comment]
@nomi9995 sure thankyou .

**Comment by rnqayush** [comment]
also @nomi9995 do it will work on ios or there too it can have issues.

**Comment by nomi9995** [comment]
@rnqayush it is specifically for android

**Comment by nomi9995** [comment]
@rnqayush can you try `0.5.3-rc.0` version

**Comment by ymane** [comment]
I am also facing same issue with "react-native-compressor": 0.5.3 and react-native: 0.64.2 
`[Error: crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported]`

**Comment by nomi9995** [comment]
@ymane can you provide reproducible example in git repo because it is not reproducing on my side

**Comment by nomi9995** [comment]
@rnqayush @ymane I just release `1.0.0` can you try the `1.0.0` version
```
yarn add react-native-compressor@1.0.0
```

**Comment by moowoonsunghoon** [comment]
i have same issue

**Comment by nomi9995** [comment]
@moowoonsunghoon can you tell me your RN version and compressor version?

**Comment by moowoonsunghoon** [comment]
@nomi9995 
my version is 
`react-native: 0.64.1`
`react-native-compressor: 1.0.1`

**Comment by nomi9995** [comment]
@moowoonsunghoon sorry for that. react-native-compressor>=1.0.0 is for `react-native@0.65`

you can use `0.5.6` version for the compressor
```
yarn add react-native-compressor@0.5.6
```
after this please do `Invalidate Caches / Restart` from android studio
![image](https://user-images.githubusercontent.com/36044436/140700293-46e5c737-4fc6-401e-a423-7dfe1aa53dc6.png)

**Comment by nomi9995** [comment]
@moowoonsunghoon i will update documentation soon

**Comment by moowoonsunghoon** [comment]
@nomi9995 
it's working!! thank you!!

**Comment by DavidGonzalezGutierrez** [comment]
Hello!
Same issue on iOS.
React Native version: 0.66.2
React Native Compressor: 1.0.2

**Comment by nomi9995** [comment]
@DavidGonzalezGutierrez can you try this `Invalidate Caches / Restart` from android studio ![image](https://user-images.githubusercontent.com/36044436/140700293-46e5c737-4fc6-401e-a423-7dfe1aa53dc6.png)

**Comment by DavidGonzalezGutierrez** [comment]
When I use UUID version 4 in my app, I always use with __DEV__ because I read the uuidv4 has problems in development mode

**Comment by nomi9995** [comment]
can you try this solution https://github.com/uuidjs/uuid/issues/416#issuecomment-651294527

**Comment by DavidGonzalezGutierrez** [comment]
Yes, It works!

**Comment by nomi9995** [comment]
@DavidGonzalezGutierrez I also have published a new version `1.0.3` of the compressor where I added above fix

**Comment by DavidGonzalezGutierrez** [comment]
Nice work!

**Comment by ahmad0303** [comment]
@nomi9995 Hello, When I use minimumFileSizeForCompress in video it changes the file format and didn't upload with the error TypeError: Network request failed
"react-native-compressor": "^0.5.17",
"react-native": "0.64.2",
It perfectly works on images but didn't work on video

**Comment by harleenarora** [comment]
Compress video is not working on android

**Comment by avyasradicle** [comment]
Hi I am using  "react-native": "0.70.1" and "react-native-compressor": "^1.7.2".
Getting error in build-

* What went wrong:
Could not determine the dependencies of task ':react-native-compressor:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':react-native-compressor:debugCompileClasspath'.
   > Could not find com.github.numandev1:VideoCompressor:1a262bba37.
     Required by:
         project :react-native-compressor

**Comment by numandev1** [comment]
@avyasradicle can you try this code and try again
```
	allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}
```

**Comment by avyasradicle** [comment]
It worked. Thank you!! :)
