### ISSUE TITLE
Unable to compress Png file in both android and ios.

### ISSUE THREAD

**Issue by krupalikevadiya** [Shobbak/react-native-compressor#33]

**Comment by krupalikevadiya** [comment]
Hey @nomi9995 thanks for reply.There is no any error log in console while compress image but image size is larger than original image size.Like my original image size is 13.12 kb and after applying image compression it will be 43 kb.

**Comment by nomi9995** [comment]
@krupalikevadiya can you try some bigger image like 1 to 5 mb

**Comment by krupalikevadiya** [comment]
No i just check it for small images like kb.But let you know result for large images after test.

**Comment by nomi9995** [comment]
@krupalikevadiya you should check this package on minimum 50kb image

**Comment by krupalikevadiya** [comment]
Hey @nomi9995 what i have to do to compress images which have size lower 50kb?

**Comment by nomi9995** [comment]
@krupalikevadiya you have to play with these three options
![image](https://user-images.githubusercontent.com/36044436/134325985-9357f4b9-2a50-4d62-aa1b-e1bbcffa3b41.png)

**Comment by krupalikevadiya** [comment]
Yes i used this all three options and use same height and width of original image with 0.5 quality but png image become double in size after compression.

**Comment by krupalikevadiya** [comment]
Hey @nomi9995 did you have any another suggestion for png image compression?

**Comment by nomi9995** [comment]
@krupalikevadiya you can add native code for less than 50kb image. I will welcome your PR
