### ISSUE TITLE
Could not find com.zolad:videoslimmer:1.0.0

### ISSUE THREAD

**Issue by thekundankamal** [Shobbak/react-native-compressor#37]
I am getting this in android ?

**Comment by srivastavaanurag79** [comment]
can you fix it i am not able to do the changes

**Comment by Harshit31** [comment]
@nomi9995 I'm also facing the same issue. Not very well versed with Andriod Development. Any help is appreciated.

**Comment by nomi9995** [comment]
@srivastavaanurag79 @Harshit31 @thekundankamal can you try `0.5.6-alpha.0` this version
```
yarn add react-native-compressor
```
i hope this version will not have any issue

**Comment by srivastavaanurag79** [comment]
Have you tested it? I tried to do the same thing in my project, changing in node_modules, it didn't worked. But I will try this new release.

**Comment by nomi9995** [comment]
@srivastavaanurag79 yes, I tested. on my side older versions are also working. can you try after clear cache
![image](https://user-images.githubusercontent.com/36044436/139590764-d8c0eb61-cebf-4d4f-b044-072852f651a8.png)

**Comment by thekundankamal** [comment]
Yes, Its working for me on the given below version..

**npm**
yarn add react-native-compressor@0.5.6-alpha.0

But we can minimise the time of compression its taking more time as compared to whatsp.

**Comment by nomi9995** [comment]
@thekundankamal sure i will work on it after some week

**Comment by nomi9995** [comment]
@srivastavaanurag79 can you verify this?

**Comment by srivastavaanurag79** [comment]
I have installed the library, it build correctly this time. Thanks

**Comment by srivastavaanurag79** [comment]
compressed a 4mb photo to 137.5kb, noice packag
![IMG_20211101_110007](https://user-images.githubusercontent.com/24560090/139625912-9f3e766b-897e-436d-985f-4b57aa6ff9bd.jpg)
e

![image](https://user-images.githubusercontent.com/24560090/139625919-47274063-ae6b-4d8a-b5e4-4550a60cf975.png)

**Comment by nomi9995** [comment]
@srivastavaanurag79 thanks. I am going to release the correct version `0.5.6` so everyone run build without this error
