### ISSUE TITLE
VideoCompressEventEmitter.removeSubscription is not a function while compress a video file

### ISSUE THREAD

**Issue by rahulll187** [Shobbak/react-native-compressor#39]
Hello,

Im getting this error while compress video in auto compression mode. 
here is my code, where

url = 'file:///data/user/0/com.qlandemo/cache/c850b3e6-6e20-49d2-a844-6102dd7243e8.mp4'

note - it's going in catch part every time & give me the error - VideoCompressEventEmitter.removeSubscription is not a function

can anyone help me to resolve it?

Thanks in advance.

```
Video.compress(
      url,
      {
        compressionMethod: 'auto',
      },
      progress => {
        if (backgroundMode) {
          console.log('ok');
        } else {
          console.log('progress', progress);
        }
      },
    )
      .then(res => console.log('res', res))
      .catch(error => console.log('err', error));
```

**Comment by nomi9995** [comment]
@rahulll187 can you tell me your `react-native` version?

**Comment by rahulll187** [comment]
@nomi9995 , my react-native version is `0.66.1`

**Comment by nomi9995** [comment]
@rahulll187 I am also using the `0.66.1` version but I am not getting this issue. can you provide a reproducible example?

**Comment by nomi9995** [comment]
@rahulll187 I just release `1.0.0` can you try the `1.0.0` version
```
yarn add react-native-compressor@1.0.0
```
