### ISSUE TITLE
index.d.ts for videoCompressorType is missing maxSize field in 1.0.3

### ISSUE THREAD

**Issue by GrandPoohBear** [Shobbak/react-native-compressor#42]
I'm adding the `maxSize` parameter to the options field for `Video.compress`, but looking at the Typescript declarations for that type in the 1.0.3 release on npm, `maxSize` is missing:

```
declare type videoCompresssionType = {
    bitrate?: number;
    compressionMethod?: compressionMethod;
};
```

Possible the declarations are stale from the last release?

**Comment by nomi9995** [comment]
@GrandPoohBear you are right, I forgot to add this. I will add this typo in the next release. thanks for indication

**Comment by nomi9995** [comment]
@GrandPoohBear i have added https://github.com/Shobbak/react-native-compressor/commit/6f6192856a0a06b0dd3c44a19a6fece79b4ce41c will be added in next release

**Comment by GrandPoohBear** [comment]
Excellent, thanks so much!
