### ISSUE TITLE
 Does it support RN 0.59? 

### ISSUE THREAD

**Issue by xb1001** [Shobbak/react-native-compressor#43]
When I use version@0.5.6,  it prompt me that an error occurred
![image](https://user-images.githubusercontent.com/32784725/141887083-723f48c8-55fe-4e6e-90e9-69d9590762da.png)

**Comment by nomi9995** [comment]
@xb1001 can you share your `build.gradle` file here, I wanna see version

**Comment by xb1001** [comment]
![image](https://user-images.githubusercontent.com/32784725/141957740-fdc26911-df90-4a27-9409-9bedb9e590c9.png)

Is this?

**Comment by xb1001** [comment]
> @xb1001 can you share your `build.gradle` file here, I wanna see version

![image](https://user-images.githubusercontent.com/32784725/141957942-982d7ee3-5d09-4998-8d58-6744b19d8220.png)
is this?

**Comment by nomi9995** [comment]
@xb1001 this file is looking good. can you add a reproducible example through the GitHub repo

**Comment by xb1001** [comment]
> @xb1001 this file is looking good. can you add a reproducible example through the GitHub repo

I notice that the project use 'androidx.annotation.RequireApi'，my project  do not support androidx, do I have other solutions for use it?

**Comment by nomi9995** [comment]
@xb1001 I think, you should add android X support in your project
https://developer.android.com/jetpack/androidx/migrate
https://medium.com/androiddevelopers/migrating-to-androidx-tip-tricks-and-guidance-88d5de238876

**Comment by xb1001** [comment]
@nomi9995 ok. I will try it. thanks
