### ISSUE TITLE
Error: Native module not found

### ISSUE THREAD

**Issue by natex-mobile-viraj** [Shobbak/react-native-compressor#44]
I have an issue with Video Compressor.
```
const result = await Video.compress('./853.mp4');
console.log('dfff', result);
```
Result - Error: Native module not found

**Comment by nomi9995** [comment]
@natex-mobile-viraj right now. we don't support bundled images. you should pass video URI like `file:///path_of_file.extension`

**Comment by swizes** [comment]
I am testing the example video compression screen

I get the same error for the "sourceVideo"

Here is the path of the file

file:///Users/swizes/Library/Developer/CoreSimulator/Devices/1CD6BFB7-2777-4C4A-83CE-B89DCA2C79EA/data/Containers/Data/Application/DE68D37D-B8BD-49D2-A9E8-DC6BE64F666C/tmp/big_buck_bunny.mp4

**Comment by nomi9995** [comment]
@swizes it seems like a linking issue. can you remove pod and reinstall pod and install build from Xcode and try again. or you can try different video?
it is not reproducing on my side.

**Comment by panvourtsis** [comment]
I have the same issue till yesterday. I removed my `Podfile.lock` and run `pod install` and suddenly I see that. I checked pod is installed.

I tried manual installing it but it breaks in another error that I cannot resolve.

**Comment by nomi9995** [comment]
@panvourtsis you are right, we added `react-native-get-random-values` in 1.0.3 version
https://github.com/Shobbak/react-native-compressor/releases/tag/v1.0.3

**Comment by swanand6300** [comment]
I have encounter the same issue and it is not working even i have installed the new release.

**Comment by nomi9995** [comment]
@swanand6300 can you install 
```
yarn add react-native-get-random-values
```
and then run `pod install` and then check?
