### ISSUE TITLE
onProgress callback for images

### ISSUE THREAD

**Issue by timges** [Shobbak/react-native-compressor#47]
Hey folks, firstly thanks for creating this library 🤙🏼  Do you have any plans on adding the onProgress callback to image-compression, aswell? Would be pretty useful imo.

**Comment by nomi9995** [comment]
@timges I will add in the next release. thanks

**Comment by timges** [comment]
Sounds great, thanks 🔥

**Comment by nomi9995** [comment]
@timges I tested 100mb image, it just takes 1 or 2 sec to compress, I think, we should not add progress for image compression because compression for an image does not take too much time, it will be overhead. what do you think?

**Comment by timges** [comment]
👍🏼
