### ISSUE TITLE
Division by zero crash in iOS when resolution is smaller than the specified output resolution

### ISSUE THREAD

**Issue by GrandPoohBear** [Shobbak/react-native-compressor#49]
Calling compress on a source video of size 848x480 (as output by Ray-Ban Stories glasses) with a desired output of 1280x720 will yield a division by zero error in the `makeVideoBitrate` function.  Specifically [this line](https://github.com/Shobbak/react-native-compressor/blob/master/ios/Video/VideoCompressor.swift#L249):

```swift
var remeasuredBitrate:Int = originalBitrate / (min(originalHeight/height,originalWidth/width))
```

Since `originalHeight` is an int, and `height` is a larger int, the result will be 0 (cuz we're doing integer division), so we'll end up dividing `originalBitrate` by 0 and creating a rift in time and space as we know it.  

Actually, the entire function is doing some integer math that might have some issues, like:

```swift
let compressFactor:Float = 0.8
// a few lines later
remeasuredBitrate = remeasuredBitrate*Int(compressFactor)
```
Coercing `compressFactor` into an int is essentially a floor function - the decimal gets rounded down to zero.  So this will always guarantee that the `remeasuredBitrate` is 0.

I'd be pleased to help advise how to fix this up, but as it's not really documented what this function is supposed to do, it's a bit tricky to tell what needs to happen solo.  Happy to discuss more!

**Comment by nomi9995** [comment]
@GrandPoohBear thanks for pointing it out. currently, I am in the office and doing a company job. I will see it when I am at home

**Comment by nomi9995** [comment]
@GrandPoohBear sorry for the late fix because I became busy with other things. 
Now you can install this version
```
yarn add react-native-compressor@1.1.1
```

**Comment by GrandPoohBear** [comment]
Looks good!  I'll update shortly.

**Comment by drash-course** [comment]
I'm still having a crash in a similar situation. The code does integer division and crashes when `width * height` is larger than `1280 * 720`.

Fixed code:
```swift
let minBitrate = Int(self.getVideoBitrateWithFactor(f: minCompressFactor) / (1280 * 720 / Float(width * height)))
```

**Comment by drash-course** [comment]
You can find a PR for the issue above. https://github.com/Shobbak/react-native-compressor/pull/73

It's not exactly on topic but I'll leave it here if someone finds this issue with the same problem as me.
