### ISSUE TITLE
Video compressionMethod manual don't work

### ISSUE THREAD

**Issue by thinnakrit** [Shobbak/react-native-compressor#54]
Video compressionMethod manual don't work

"react-native": "0.63.4",
"react-native-compressor": "^1.1.1",

```
const result = await VideoCompressor.compress(
				video.path,
				{
				},
				(progress) => {
				```

**Comment by nomi9995** [comment]
@thinnakrit can you tell me the error which you are getting by using try-catch ?

**Comment by nomi9995** [comment]
@thinnakrit feel free to reopen if you get this issue again
