### ISSUE TITLE
Auto Video compression Method not working getting "Native module not found" error

### ISSUE THREAD

**Issue by workhexaloop** [Shobbak/react-native-compressor#55]
Auto Video compression Method not working getting **"Native module not found"**  error

 Video compression **working** with this version:
"react": "17.0.1",
"react-native": "0.64.2",
"react-native-compressor": "^0.5.3",

 Video compression **not working** with this version:
"react": "17.0.2",
"react-native": "0.66.1",
"react-native-compressor": "^1.1.1"

This is the code which we are using: 

```
await Video.compress(filePath,
                { compressionMethod: 'auto' },
                (progress) => { isCompress = true }
            ).then((path) => {
                console.log(path, 'compressed path');
                
            }).catch((err) => { alert("err: "+err); })

```

Attached the error screenshot also:

![WhatsApp Image 2021-12-11 at 12 02 32 PM](https://user-images.githubusercontent.com/62990470/145666961-966ee217-38d7-466c-94ae-e9511e020f2e.jpeg)

**Comment by nomi9995** [comment]
@workhexaloop you can install `react-native-get-random-values` manually and check
```
yarn add yarn add react-native-get-random-values
```

**Comment by workhexaloop** [comment]
Thanks @nomi9995 its working now.
