### ISSUE TITLE
how to add video resizemode props while compress (react-native-compressor@0.5.6)?

### ISSUE THREAD

**Issue by chickho** [Shobbak/react-native-compressor#58]

**Comment by nomi9995** [comment]
@chickho resize mode contain is already applied to every video. why do you need this prop

**Comment by chickho** [comment]
because the result of the video that I compressed is landscape(resize mode:stretch) while the original video is portrait(resizemode:"cover")

**Comment by nomi9995** [comment]
@chickho can you attach that video so i can test and which platform, you are using Android or IOS?

**Comment by nomi9995** [comment]
I think it is already fixed. feel free to reopen if you see this problem again.
