### ISSUE TITLE
Video is not resizing 

### ISSUE THREAD

**Issue by unoegohh** [Shobbak/react-native-compressor#65]
Hi!  I am having troubles with video compression
```
"react-native-compressor": "1.2.0"
"react-native": "0.66.1"
```
```

Video.compress(file.path, {
        // compressionMethod: 'manual',
        //minimumFileSizeForCompress: 10,
        maxSize: 100,
      })
        .then(res => {...})
        .catch(console.log);

```
 [original file](https://drive.google.com/file/d/13lRRcXOnlezktSpDnZORSa1GW06XeGIU/view?usp=sharing)
original file is 42mb 1080 × 1920 30 sec
compressed always 3.2 mb 360 × 568  

i need to do something to make video 600x1000
i have tried all params from doc but nothing changes( mb i am doing something wrong
and i tried different video

**Comment by nomi9995** [comment]
@unoegohh let me see it

**Comment by nomi9995** [comment]
@unoegohh are you want manual compression or auto compression-like WhatsApp?

**Comment by nomi9995** [comment]
@unoegohh if I use `maxSize: 1000` then I am getting `562x1000` resolution of the video which you have attached

```
const dstUrl = await Video.compress(
      sourceVideo,
      {
        compressionMethod: 'auto',
        minimumFileSizeForCompress: 5,
        maxSize: 1000,
      },
      (progress) => {
        if (backgroundMode) {
          console.log('Compression Progress: ', progress);
        } else {
          setCompressingProgress(progress);
        }
      }
    );
```

**Comment by unoegohh** [comment]
Hmm it is strange cause if i use 


```
import {Video as VideoCompressor} from 'react-native-compressor';

VideoCompressor.compress(file.path, {
        compressionMethod: 'auto',
        minimumFileSizeForCompress: 5,
        maxSize: 1000,
      })
        .then(res => {
          console.log('video', res);
        })
        .catch(console.log);
```

and then i get 

`video1 file:///Users/unoegohh/Library/Developer/CoreSimulator/Devices/C856B11B-463E-48F6-9396-5F4E0838CDC2/data/Containers/Data/Application/60489947-00AB-49D1-A5F0-E72164EDD6D5/tmp/react-native-image-crop-picker/F6B9FBB8-4C2A-4882-ABBC-A3E9BFE8A0C7.mp4`

and it is still get 320x564 video

[file](https://drive.google.com/file/d/1UbQRoG61AJI11B5-TUr_88yGs_CQQqW9/view?usp=sharing)

**Comment by unoegohh** [comment]
Hmm it is strange cause if i use 


```
import {Video as VideoCompressor} from 'react-native-compressor';

VideoCompressor.compress(file.path, {
        compressionMethod: 'auto',
        minimumFileSizeForCompress: 5,
        maxSize: 1000,
      })
        .then(res => {
          console.log('video', res);
        })
        .catch(console.log);
```

and then i get 

`video1 file:///Users/unoegohh/Library/Developer/CoreSimulator/Devices/C856B11B-463E-48F6-9396-5F4E0838CDC2/data/Containers/Data/Application/60489947-00AB-49D1-A5F0-E72164EDD6D5/tmp/react-native-image-crop-picker/F6B9FBB8-4C2A-4882-ABBC-A3E9BFE8A0C7.mp4`

and it is still get 320x564 video

[file](https://drive.google.com/file/d/1UbQRoG61AJI11B5-TUr_88yGs_CQQqW9/view?usp=sharing)

**Comment by nomi9995** [comment]
@unoegohh yes `react-native-image-crop-picker =>. openPicker` is compressing video by reducing video height and width.

**Comment by nomi9995** [comment]
I think it is already fixed. feel free to reopen if you see this problem again. thanks.
