### ISSUE TITLE
[IOS] Failed to use "ph:://" image uri

### ISSUE THREAD

**Issue by antoshindanil** [Shobbak/react-native-compressor#71]
### Current behavior
Throw error with cannot read file
`Error processing request body: Error Domain=NSCocoaErrorDomain Code=260 "Не удалось открыть файл «C25D1B52-2740-494B-9FDC-6E69449B7DF0.jpg», так как такого файла не существует." UserInfo={NSFilePath=/private/var/mobile/Containers/Data/Application/711CAA50-1640-46E5-8E0A-86B9C439414E/tmp/C25D1B52-2740-494B-9FDC-6E69449B7DF0.jpg, NSUnderlyingError=0x2829d3660 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
`

example uri `ph://3740F77F-A886-4BEA-8B2C-47D8030A06CD/L0/001`

### Expected behavior
Read and compress file

### Platform
- [ ] iOS

### React Native Version
"react-native": "^0.66.4",

### React Native Compressor Version
"react-native-compressor": "^1.2.1",

### Reproduction
1. Take image from "@react-native-community/cameraroll" on IOS with uri like "ph:://"
2. Pass that uri in compress with { compressionMethod: 'auto' } params

**Comment by nomi9995** [comment]
@antoshindanil can you attach a reproducible example here?

**Comment by nomi9995** [comment]
@antoshindanil fixed by `1.4.0` version
