### ISSUE TITLE
Facing issue when compressing a video in android, it's orientation getting changed.

### ISSUE THREAD

**Issue by govind-v-natex** [Shobbak/react-native-compressor#72]
when compressing a video recorded from the android mobile in vertical direction, after compressing it, it's orientation is getting changed to horizontal.

This issue is only in the video recorded from the android device, any video we are downloading and compressing it's working fine, please have a look into this @nomi9995

**Comment by nomi9995** [comment]
@govind-v-natex can you provide video so i can test it on my side?

**Comment by govind-v-natex** [comment]
Sure I'm sharing the video over mail @nomi9995

**Comment by govind-v-natex** [comment]
But @nomi9995 , the bug can be tested only if you record the video from the android device and try to compress, if i share the recorded video and you download it and test it, will work fine.

**Comment by govind-v-natex** [comment]
@nomi9995 Any update on this ?

**Comment by govind-v-natex** [comment]
@nomi9995 Any update on this, we are in between something, please have a look on priority basis.

**Comment by nomi9995** [comment]
@govind-v-natex I am going to release a new version of the compressor. it has been fixed. I will let you know when i release new version

**Comment by nomi9995** [comment]
@govind-v-natex can you check `1.3.2` version?

**Comment by govind-v-natex** [comment]
Sure, I'm checking @nomi9995
