### ISSUE TITLE
[SUGGESTION ] - Replace VideoSlimer as video compressor on Android

### ISSUE THREAD

**Issue by emmbyiringiro** [Shobbak/react-native-compressor#78]
https://github.com/zolad/VideoSlimmer seems like not work well with video with modern aspect ratios.

If you do various tests on various video aspect ratios, the module works well with traditional ratios like `4:3` or `16:9`.

While rotating video on a modern ratio like `18:9` on `1920x1080`. This also happens in the test video by the module author.

Author compress video with `1920x1080` and output becomes `200x360`, The video actually reversed.
![Screen Shot 2022-01-09 at 1 46 04 AM](https://user-images.githubusercontent.com/46843540/148665018-5e09ffed-a767-4e13-aa06-720ff762e010.png)

**Comment by nomi9995** [comment]
@emmbyiringiro i already replace you can check in build.gradle.
