### ISSUE TITLE
Video can't play after compression in android

### ISSUE THREAD

**Issue by cenim** [Shobbak/react-native-compressor#79]

**Comment by cenim** [comment]
This is the code segment

`compressVideo = async (uri) => {
        this.setState({ showLoader: true })

        //To avoid name conflict with default react native class Video
        //import * as Compressor from 'react-native-compressor';

         let result = await Compressor['Video'].compress(uri, {
            compressionMethod: 'auto',
        }).then(res => {


            this.setState({ showLoader: false })
             
            this.setState({ compressed: res })
                 this.saveImage(res)

          
 
        });

    }`

**Comment by cenim** [comment]
Only works on IOS, video corrupts on android after compression

**Comment by nomi9995** [comment]
@cenim can you attach video you are trying to compress?

**Comment by cenim** [comment]
> @cenim can you attach video you are trying to compress?

**Comment by cenim** [comment]
Can't upload since file max here size is 10mb. I've tested on 2 phones. A12 samsung and Pixel 3. On Android, image compression works fine but video can't be played after compression. IOS however, both compressions work perfectly. I don't know if I'm doing something wrong in the android...

**Comment by cenim** [comment]
> @cenim can you attach video you are trying to compress?

https://drive.google.com/file/d/1bV3Q8wZSxhkQt5xbSIgsWhqAwYECM2Lb/view?usp=sharing

**Comment by nomi9995** [comment]
@cenim it is working on my side, here is a compressed video of your
https://drive.google.com/file/d/1xwqLBWo9vHWBayBRWLMyDW83Ml1EwYwS/view?usp=sharing

**Comment by nomi9995** [comment]
@cenim now I got your point, the android compressor is compressing video without sound and your server is not supported without sound video. let me fix it 

i think, @govind-v-natex also have same type of issue.

**Comment by cenim** [comment]
What do I change then?

**Comment by cenim** [comment]
> @cenim now I got your point, the android compressor is compressing video without sound and your server is not supported without sound video. let me fix it
> 
> i think, @govind-v-natex also have same type of issue.
Ok I'm waiting

**Comment by nomi9995** [comment]
@cenim now you can use `1.3.4` version.
```
yarn add react-native-compressor@1.3.4
```

**Comment by cenim** [comment]
> @cenim now you can use `1.3.4` version.
> 
> ```
> yarn add react-native-compressor@1.3.4
> ```

Issue persisting. Probably something different other than sound.
The compressed video is black and can't play at all.
![Screenshot_20220112-132219](https://user-images.githubusercontent.com/29374116/149148512-141e607c-37fc-4ea0-8c3d-15aa1d4a4d5d.jpg)

**Comment by nomi9995** [comment]
@cenim can you try to compress the video from the example folder of this package. it is working on our side.

here is your compressed video.
https://user-images.githubusercontent.com/36044436/149149038-fa690681-e8f9-40c6-8b15-935548619ce8.mp4

**Comment by nomi9995** [comment]
@cenim if you connect with me on LinkedIn than i can see this issue on your machine if you want.

**Comment by cenim** [comment]
> Only works on IOS, video corrupts on android after compression



> Only works on IOS, video corrupts on android after compression

I figured it out. The directory for videos after compression in android should be `file:///` not `file://`. So I just replaced that in the res:

`result.replace("file://","file:///" )`

Thanks a lot

**Comment by nomi9995** [comment]
@cenim thanks, I will implement `///` for android in next release.

you find this package useful than hit the star for support to this package.

**Comment by sdcooke** [comment]
@cenim did the update and `file:///` changes definitely fix it for you? I'm having the same issue after both of those fixes. The compressed video is blank when played on the iOS simulator, Finder on a mac, or VLC and has glitchy green artefacts in Quicktime. I've been using `ffprobe` to look at the differences between a file encoded on the iOS simulator and an Android device (Pixel 4a) and can't see anything obviously wrong with the Android output - no errors, just slightly different formats.

@nomi9995 love this package, it's exactly what I needed and seems to work great on iOS so far. You mentioned an example file I could try it on but I couldn't see that in this repo.

Thanks!

**Comment by nomi9995** [comment]
@sdcooke means it is working with the example file of this project but not working in your project?

**Comment by sdcooke** [comment]
Sorry - I hadn't spotted the sample links in the spreadsheet! I just tried with https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_20mb.mp4 and am seeing the same issue. In auto mode it gets compressed to this https://www.dropbox.com/s/1c82qjjdvi2ip4r/IMG_0019.MP4?dl=0 which looks like this when I play in Quicktime on my mac, and is just blank on the iOS simulator. 
![Screenshot 2022-01-14 at 10 02 10](https://user-images.githubusercontent.com/136235/149497099-4b9861da-bdd0-4758-902a-7b8b4e37d66d.png)

**Comment by sdcooke** [comment]
This sample video https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_20mb.mp4 failed for me - it compressed to https://www.dropbox.com/s/1c82qjjdvi2ip4r/IMG_0019.MP4?dl=0 which doesn't play on iOS or Quicktime.
