### ISSUE TITLE
Color issues with HDR video on iOS

### ISSUE THREAD

**Issue by sdcooke** [Shobbak/react-native-compressor#81]
HDR videos (such as those recorded by the default camera on iOS) do not display correctly after compression on iOS. They look right on macos, but I'm assuming that's because I do not have an HDR display on my mac but the iPhone 13 Pro and Pixel 4a are trying to display as HDR. The colors are incorrect.

I used this sample video https://img.photographyblog.com/reviews/apple_iphone_13/sample_images/4K_60fps.mov (from https://www.photographyblog.com/reviews/apple_iphone_13_review) and got this output https://www.dropbox.com/s/4v54u393dfca80p/IMG_0022.MP4?dl=0.

Using ffprobe it looks like maybe the color space metadata of the video is transferred over to the compressed video but maybe the data is not HDR? I'm not sure about that, though.

Using the latest version of react-native-compressor (1.3.4) and react-native 0.66.3.

**Comment by nomi9995** [comment]
@sdcooke as far as i know, we are compression high-resolution video to 640 max resolution, can you try with increase `maxSize` llike
```
maxSize:1280
```
https://github.com/Shobbak/react-native-compressor#maxsize-number-default-640

**Comment by nomi9995** [comment]
@sdcooke any update on this issue?

**Comment by sdcooke** [comment]
Hi @nomi9995 sorry I missed your previous message! I ended up writing my own video compressor module so that I could work through the issues and get it working quicker. I used https://github.com/AbedElazizShe/LightCompressor_iOS/ as inspiration for iOS and didn't have any issues with HDR.
