### ISSUE TITLE
Return compressed video metadata

### ISSUE THREAD

**Issue by emmbyiringiro** [Shobbak/react-native-compressor#82]
Currently, implementation return only compressed video `uri`, this work well in most situation but in some situation, video extra metadata like `width`, `height`, `size`, `duration`, `extension` and more are required when user need those metadata to control video base on them.

Is any plan to expose metadata for video?

**Comment by nomi9995** [comment]
@emmbyiringiro I hope, I will add this in the next version.

**Comment by nomi9995** [comment]
@emmbyiringiro can you try alpha version
```
yarn add react-native-compressor@alpha
```
here is the docs for meta data function
https://github.com/Shobbak/react-native-compressor#get-metadata-of-video

**Comment by iMatheusouza** [comment]
Hey, theres a way to get image compressed metadata, like the getVideoMetaData feature, extra infos like `width`, `height`, `size`?

**Comment by ursnj** [comment]
Hey Do we have any image metadata option with this library ???
