### ISSUE TITLE
Error after adding module and starting expo project

### ISSUE THREAD

**Issue by pihomeserver** [Shobbak/react-native-compressor#86]
### Current behavior
```
Invariant Violation: Native module cannot be null.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-runtime/src/polyfills/require.js:204:6 in guardedLoadModule
at http://192.168.31.95:19000/index.bundle?platform=ios&dev=true&hot=false&minify=false:264912:3 in global code
```

### Expected behavior
App starts

### Platform

- [X] iOS (Android not tested)

### React Native Version
Expo 44 and RN 0.64.3

### React Native Compressor Version
1.5.0

### Reproducible Steps And Demo
Install via yarn add or expo cli
Check that the app.json has been updated with the plugin property
Restart via expo start

Here is the full error message
```
Invariant Violation: Native module cannot be null.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-runtime/src/polyfills/require.js:204:6 in guardedLoadModule
at http://192.168.31.95:19000/index.bundle?platform=ios&dev=true&hot=false&minify=false:264912:3 in global code

Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
```

I don't import the library in any file
If i remove the plugin property, app starts. As soon as i import the library in a component the error raises again

**Comment by nomi9995** [comment]
@pihomeserver can you try this version and let me know?
```
yarn add react-native-compressor@rnlessthan65
```

**Comment by pihomeserver** [comment]
RTFM ... Sorry

Unfortunatly i can do one step more but still get the error
I remove the package, reinstalled the one for RN < 0.65, checked the app.json entry with plugin property, executed the "expo prebuild -p ios" command
The app load works
As soon as i add the following line i got the same error
```
import { Image as ImageCompressor } from 'react-native-compressor';
```

**Comment by nomi9995** [comment]
@pihomeserver
@emmbyiringiro is using `react-native-compressor` for the expo. it is working fine for @emmbyiringiro. can you give me a reproducible example so I can see where is the actual problem?

**Comment by pihomeserver** [comment]
Maybe i miss used it or do a syntax error
I created a new expo project `expo init compress`
Then install the lib `yarn add react-native-compressor@rnlessthan65`
Append the plugin property to app.json
```
{
  "expo": {
    "name": "compress",
    "slug": "compress",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#FFFFFF"
      }
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "plugins": ["react-native-compressor"]
  }
}
```
Then change the default App.json content to the following
```
import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View } from 'react-native';
import { Image as ImageCompressor } from 'react-native-compressor';

export default function App() {

  ImageCompressor.compress('').then(()=>{}).catch((e)=>{})

  return (
    <View style={styles.container}>
      <Text>Open up App.tsx to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```
And then start expo with `expo start -c`
I got the error again
I tried to execute the prebuild command before but then i have an error on it 
```
chris@MBP-de-Chris compress % expo prebuild -p ios --clean
Warning! Your git working tree is dirty.
It's recommended to commit all your changes before proceeding, so you can revert the changes made by this command if necessary.

✔ Would you like to proceed? … yes

✔ Cleared ios code
✔ Created native project | gitignore already synced
✔ Updated package.json and added index.js entry point for iOS and Android
🧶 Using Yarn to install packages. Pass --npm to use npm instead.
✔ Installed JavaScript dependencies 961ms
✔ Config synced
⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: Invalid `Podfile` file: undefined method `post_integrate' for #<Pod::Podfile:0x00007fdce0adfe98>
Did you mean?  post_install.

 #  from /Users/chris/Development/compress/ios/Podfile:41
 #  -------------------------------------------
 #
 >    post_integrate do |installer|
 #      begin
 #  -------------------------------------------
```
Not sure if it's related. I never executed this command before, even before building/deploying my app to the store

**Comment by nomi9995** [comment]
@pihomeserver can you attach this repro in GitHub repo?

**Comment by pihomeserver** [comment]
Here a repo generating the error : https://github.com/pihomeserver/compressTest

**Comment by emmbyiringiro** [comment]
@pihomeserver  could you use EAS  - https://docs.expo.dev/eas/ it worked well for me and I hope it should be the same for you. We can have a 1-to-1 meeting in case you need further assistance

**Comment by pihomeserver** [comment]
For my understanding EAS is for app management (build and publish). What about the development and live test with the expo app ?

**Comment by emmbyiringiro** [comment]
Take look Expo founder tutorial on how to use this feature in development - https://www.youtube.com/watch?v=id0Im72UN6w

**Comment by pihomeserver** [comment]
Unable to build it 
```
Installing pods
Using Expo modules
Auto-linking React Native modules for target `Inspiratin`: RNGestureHandler, RNReanimated, RNSVG, RNScreens, react-native-compressor, react-native-safe-area-context, and react-native-sqlite-storage
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/`
CocoaPods 1.11.2 is available.
To update use: `sudo gem install cocoapods`
For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.11.2
[!] Unable to find a specification for `UMCore` depended upon by `EXPermissions`
You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
[stderr] [!] `<PBXResourcesBuildPhase UUID=`13B07F8E1A680F5B00A75B9A`>` attempted to initialize an object with an unknown UUID. `81A95CE5B8AF4082BEBA0FE0` for attribute: `files`. This can be the result of a merge and the unknown UUID is being discarded.
pod exited with non-zero code: 1
```

I guess there is something wrong in the ios pods ...

**Comment by nomi9995** [comment]
@pihomeserver can you try this command and try to build again
```
sudo gem install cocoapods
pod install --repo-update
```

**Comment by pihomeserver** [comment]
I tried it (as it's in the log) but i still continue to have the message of the potential upgrade : 

```
chris@MBP-de-Chris ios % sudo gem install cocoapods
Password:
Successfully installed cocoapods-1.11.2
Parsing documentation for cocoapods-1.11.2
Done installing documentation for cocoapods after 1 seconds
1 gem installed
chris@MBP-de-Chris ios % pod install --repo-update
Using Expo modules
Auto-linking React Native modules for target `Inspiratin`: RNGestureHandler, RNReanimated, RNSVG, RNScreens, react-native-compressor, react-native-safe-area-context, and react-native-sqlite-storage
Updating local specs repositories

CocoaPods 1.11.2 is available.
To update use: `sudo gem install cocoapods`

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.11.2

Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
[!] Failed to load 'expo-dev-client' podspec:
[!] Invalid `expo-dev-client.podspec` file: [!] Unsupported version requirements. [{:configurations=>:debug}] is not valid..

 #  from /Users/chris/Development/Inspiration/node_modules/expo-dev-client/ios/expo-dev-client.podspec:18
 #  -------------------------------------------
 #
 >    s.dependency 'expo-dev-launcher', :configurations => :debug
 #    s.dependency 'expo-dev-menu', :configurations => :debug
 #  -------------------------------------------


[!] `<PBXResourcesBuildPhase UUID=`13B07F8E1A680F5B00A75B9A`>` attempted to initialize an object with an unknown UUID. `081DCB6B977C4E4A963B1D2B` for attribute: `files`. This can be the result of a merge and  the unknown UUID is being discarded.
```

**Comment by nomi9995** [comment]
@pihomeserver can you add this repro example in GitHub and share URL so we can see it on local machine and fix it.

**Comment by pihomeserver** [comment]
I think there are other issues somewhere. I created the basic project, perform a `eas build --profile development --platform ios` then when i open the app on my iPad, it blocks on the splash screen and crash ...
I will try to solve that first before adding the lib :-(

**Comment by emmbyiringiro** [comment]
@pihomeserver  can we have a meeting if you can? i wish I can help

**Comment by pihomeserver** [comment]
Ok found a solution : i upgraded cocoapods with brew and gem (i installed both)  then i had an issue with fastlane (i had to install it manually), then i had an issue with EXPermission (i installed it with expo install) then i could install and deploy with eas, including the compressor package !
Still have some bugs (screen rotation is not well managed) but it works and i can call compress method !

Thank you guys !

**Comment by nomi9995** [comment]
> @nomi9995 Thank you for that, the link: #86 was perfect in regards the iOS detail, nonetheless, getting a similiar issue in which if I add the import of the module, I will get:
> 
> Invariant Violation: Native module cannot be null. at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError at node_modules/metro-runtime/src/polyfills/require.js:204:6 in guardedLoadModule at http://192.168.1.65:19000/index.bundle?platform=ios&dev=true&hot=false&minify=false:121654:3 in global code
> 
> Invariant Violation: "main" has not been registered. This can happen if:
> 
> * Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
> * A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
>   at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
>   at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
>   at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
>   at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
> 
> Tried:
> 
> * yarn add react-native-compressor@rnlessthan65
>   (up to here I could open the app, but commenting the import, so definately a step forward)
> 
> -cd ios -pod install -remove your yarn.lock or package-lock.json -remove node_modules -run yarn or npm install
> 
> As for Android:
> 
> [Unhandled promise rejection: TypeError: null is not an object (evaluating 'NativeVideoCompressor.compress')] at node_modules/react-native-compressor/src/Video/index.tsx:156:48 in compress at node_modules/react-native-compressor/src/Video/index.tsx:113:12 in compress at helpers.js:6:25 in CompressVideo at helpers.js:4:17 in CompressVideo at App.js:40:24 in requestMultiplePermissions

@pihomeserver @emmbyiringiro what do you think about this issue?
