### ISSUE TITLE
iOS issue after upgrading Xcode 13.2.1

### ISSUE THREAD

**Issue by martsneld** [Shobbak/react-native-compressor#87]
### Current behavior
/Users/mycom/Library/Developer/Xcode/DerivedData/limelite-fmzrscpebfdblueckvpunppvzdku/Build/Intermediates.noindex/PrecompiledHeaders/Compressor-Bridging-Header-xsfx0gcl0s08.dia:1:1: warning: Could not read serialized diagnostics file: error("Failed to open diagnostics file") (in target 'Compressor' from project 'Compressor')
Command PrecompileSwiftBridgingHeader failed with a nonzero exit code

### Platform

- [X] iOS

### React Native Version
0.63.3
### React Native Compressor Version
1.4.0

**Comment by martsneld** [comment]
@nomi9995 Could you check the errors above? I added node_modules/react-native-compressor/ios/Compress.xcodeproj to library and added libCompressor.a to `Link biary with libraries`.

**Comment by nomi9995** [comment]
@martsneld can you try to bridge the header by

![image](https://user-images.githubusercontent.com/36044436/152235901-d3e2ac8a-b4fd-474a-91b3-6d2a06d3d2a4.png)

![image](https://user-images.githubusercontent.com/36044436/152235678-7215cb1b-b754-4130-a48a-f25b137ff101.png)

![image](https://user-images.githubusercontent.com/36044436/152236070-7c33016d-f3e7-4111-af8b-73b268c6cdb3.png)

and try again?

**Comment by martsneld** [comment]
@nomi9995 I tried it several times. I created a blank .swift file and created a bridge. Then I dragged Compressor-Bridging-Header.h to Object-C Bridging Header.

**Comment by nomi9995** [comment]
@martsneld can you make a repro in the new GitHub repo and attach the link here so I can reproduce it on my side ad fix it. it is not reproducing on my side. I am testing the example folder in this package

**Comment by nomi9995** [comment]
@martsneld any update?

**Comment by martsneld** [comment]
@nomi9995 Sorry for late response. no updates. I disabled this library for now. I will let you know if I have more questions when resuming this package.
