### ISSUE TITLE
Upload formdata using backgroundUpload

### ISSUE THREAD

**Issue by hkhan6916** [Shobbak/react-native-compressor#88]
Currently this packages allows for uploading files in the background following compression. However, I have not been able to figure out if there's a way to upload other pieces of data with the media. E.g. sending information such as the title and description of the media file alongside the file itself. This feature would greatly improve background uploads. 

Really appreciate the work gone into this package btw, thank you.

**Comment by nomi9995** [comment]
@hkhan6916 thanks, i will add this soon.

**Comment by haibert** [comment]
Hi @nomi9995 

Thank you for this amazing library, specially for the expo support. I cant wait to be able to add data along with the background upload. Would be greatly appreciated.

**Comment by hkhan6916** [comment]
> Hi @nomi9995
> 
> Thank you for this amazing library, specially for the expo support. I cant wait to be able to add data along with the background upload. Would be greatly appreciated.

Hey @haibert, thought i'd help out as i've found a pretty good solution until @nomi9995 gets a chance to implement something more convenient. Turns out you can trigger external functions following compression. I used react-native-background-upload for ios and android. You can use it like so... 
`await VideoCompress.compress(
        file://pathToFile,
        {
          compressionMethod: "auto",
        },
        (progress) => {
          console.log({ compression: progress });
        }
      ).then(async (compressedUrl) => {
        // Then trigger the code for react-native-background-upload. 
        Docs - https://github.com/Vydia/react-native-background-upload
      });`

**Comment by haibert** [comment]
@hkhan6916 

Thank you so much for the thought and consideration. Unfortunately it seems like id need to eject expo to use react-native-background-upload which is not an option for us right now. 

Expo is amazing, really hope the community fully embraces it as RN progresses

**Comment by haibert** [comment]
@hkhan6916 

Oh I do too! I use a custom build client. 


Just to be clear are you saying that you are using eas build with react-native-background-upload ? 

Meaning we're you able to get react-native-background-upload working without ejecting? Or you were just speaking in generalities

**Comment by nomi9995** [comment]
@hkhan6916 @haibert sorry, I am too much busy with office work these days, I hope I will add formdata at the start of next week. thanks

**Comment by hkhan6916** [comment]
> @hkhan6916 
> 
> Oh I do too! I use a custom build client. 
> 
> 
> Just to be clear are you saying that you are using eas build with react-native-background-upload ? 
> 
> Meaning we're you able to get react-native-background-upload working without ejecting? Or you were just speaking in generalities 

@haibert Yes. Just install and run EAS build.

**Comment by haibert** [comment]
@nomi9995 no worries my man. we really appriciate it. cant wait for the feature!

**Comment by haibert** [comment]
@hkhan6916 sorry to bug you again but the documentation for react-native-background-upload is not very thorough. how were you able to send the body ? It also doesn't have a body param. It looks like it has a "parameters" option but doesnt really say how to use it. do you turn your data into json and put it inside the parameters ? id love to see your code for the usage

**Comment by hkhan6916** [comment]
Hey @haibert  sorry for the late response. In case you still need help, my code looks like:     `const options = {
      url: "someurl",
      path: somePathToFile,
      method: "POST",
      type: "multipart",
      maxRetries: 2,
      headers: {
        "content-type": "multipart/form-data", // IMPORTANT
        Authorization: `Bearer ${token}`,
      },
      parameters: {
        postId: post?._id, // any extra data i want to send alongside the file
      },
      field: "file",
      // Below are options only supported on Android
      notification: {
        enabled: false,
      },
      useUtf8Charset: true,
    };
    Upload.startUpload(options)`

**Comment by haibert** [comment]
@hkhan6916 no worries thank you so much!  I gotta talk to the backend guys to make sure they make changes since the request is not going to be a JSON anymore. And i'm curious do you know what format the backend will receive the actual file in ? meaning is this going to send the base64 of the file to the server or... ?
