### ISSUE TITLE
Couldn't install Pods

### ISSUE THREAD

**Issue by rocketvilas** [Shobbak/react-native-compressor#89]
### Platform

- [X] Android
- [X] iOS

### React Native Compressor Version:1.5.0

[!] CocoaPods could not find compatible versions for pod "react-native-compressor":
  In Podfile:
    react-native-compressor (from `../node_modules/react-native-compressor`)

Specs satisfying the `react-native-compressor (from `../node_modules/react-native-compressor`)` dependency were found, but they required a higher minimum deployment target.

**Comment by nomi9995** [comment]
@rocketvilas can you check the `podspec` path of compress if it exists or not
`node_modules/react-native-compressor/react-native-compressor.podspec`

**Comment by rocketvilas** [comment]
It exists.

**Comment by nomi9995** [comment]
@rocketvilas I think, you have to increase minimum deployment target to 11.0

**Comment by rocketvilas** [comment]
It's currently at 12.0

**Comment by nomi9995** [comment]
@rocketvilas any update?
