### ISSUE TITLE
Video resolution distorted

### ISSUE THREAD

**Issue by timges** [Shobbak/react-native-compressor#91]
### Current behavior
- Aspect ratio of the video is distorted after compression

### Expected behavior
- Video has the same aspect ratio as before the compression

### Platform

- [x] Android v11 (Samsung Note 10Plus & Samsung A 72)
- [ ] iOS

### React Native Version
0.66.4

### React Native Compressor Version
1.3.4

sounds similar to issue https://github.com/Shobbak/react-native-compressor/issues/77

 \
\
\
Keep up the great work. Thanks in advance 🤙🏼

**Comment by nomi9995** [comment]
@timges this was fixed. can you try `1.5.0` version?

**Comment by timges** [comment]
@nomi9995 The issue got fixed with 0.5.14 which was released before 1.3.4. Means 1.3.4 should already include the fix, shouldn't it?

**Comment by nomi9995** [comment]
I did not remember I actually cherry-pick correctly in `0.5.14` or not

you are using RN@0.66.4 then you should use the latest version which is`1.5.1` video resolution was exists in the older version. if. you use the latest version then android compression speed will also increase.

**Comment by timges** [comment]
Okay, we'll give it a try. I'll update you, when feedback is available.

**Comment by nomi9995** [comment]
@timges any update?

**Comment by timges** [comment]
@nomi9995 We are still checking with the users, but it seems to be fixed 👍🏼 Thanks for the effort.
