### ISSUE TITLE
iOS app crashes when trying to compress video from the Photos app

### ISSUE THREAD

**Issue by alariej** [Shobbak/react-native-compressor#93]
Hello and thanks for publishing this library.

`react-native-compressor` crashes my iOS app when attempting to compress a video which is loaded from the iOS Photos app. Video is shot using the phone's camera. If I first save the video from the Photos app to a local folder on the device (using "Save to Files" in Photos' share menu), then the compression on that saved file is successful and I get no crash.

When debugging in xCode, the failure appears at line 295 in VideoCompressor.swift:

`height: Int(resultHeight), width: Int(resultWidth)` -> **Thread 23: Swift runtime failure: Float value cannot be converted to Int because the result would be less than Int.min**

It is as if the original videos from the Photos app were missing the height/width information. But note that the videos always play fine in my app's video player and the files always return the correct metadata (using `getVideoMetaData`), even the ones that crash the library.

The code I use to call the library:

```
const response = await Video.compress(
    file.uri,
    {
        compressionMethod: 'auto',
        maxSize: 1024,
        minimumFileSizeForCompress: 5,
    },
    progress => console.log(progress)
)
    .catch(err => console.log(err));

```

**Comment by nomi9995** [comment]
@alariej can you send me video so i can reproduce it on my side and fix it?

**Comment by alariej** [comment]
A Share Extension in iOS allows you to share content (links, images, videos, files) from other apps into your app, using the standard iOS "Share" button. For example, if you go to the Photos library on iPhone, pick an image or a video, press on the "Share" button (lower left), you can then select an app (Mail, WhatsApp, Safari, etc.)  which you want to share the content with. You can implement that sharing functionality in React Native using, for example, https://www.npmjs.com/package/react-native-share-menu. They have good walk-through instructions at https://github.com/meedan/react-native-share-menu/blob/master/IOS_INSTRUCTIONS.md. I think this is a pretty standard way to load content into apps, so it would be great if your library could support it.

**Comment by GrandPoohBear** [comment]
My team has seen the issue where compressed files don't have any video track, and we've been trying to track it down.  There was one video that would reproduce the situation every time, but only from our tester's phone.  Any time we tried to repro on other devices, the compression worked fine.  🤷🏻

I opened an issue against NextLevelSessionExporter (the lib doing the heavy lifting on iOS), but haven't gotten anything to go on: https://github.com/NextLevel/NextLevelSessionExporter/issues/38

**Comment by alariej** [comment]
@nomi9995 The more I read about this issue, the more I think it has nothing to do with react-native-compressor. The problem seems to be with the way videos are stored in the Photos library on iOS. They cannot be imported into an app the same way as for images. Let me investigate this further, I will come back soon with what I can find out.

**Comment by GrandPoohBear** [comment]
I would definitely recommend copying the file to the app’s documents directory before doing anything else you need it for.  The OS gives you no guarantees about how long other files in other places will be available!

**Comment by nomi9995** [comment]
@alariej can you share URI of video which you get from share extension i wanna see URI scheme and other things?

**Comment by alariej** [comment]
The videos in the Photos library are accessible by the Share Extension with a URI of this type:

`file:///var/mobile/Media/PhotoData/OutgoingTemp/FC268169-1522-47C1-84E6-F71584EA5C69/Compatible/IMG_0985.MOV`

However this URI cannot be forwarded from the Share Extension to the iOS app. Its content must first be copied to a folder ("container") shared between the Share Extension and the app. In Swift this is done by doing: `FileManager.default.copyItem(sourceURI, destinationURI)`. The destination (or shared) URI then looks like:

`file:///private/var/mobile/Containers/Shared/AppGroup/751639A9-C56D-47E8-8A4E-1BF1AA5084E3/share.MOV`

It is this last URI which can be used in the app to play the video (for example, in a video player embedded in a WebView), or be posted to an external server (for example, via `rn-fetch-blob`). Both these operations work without problem. However, when I try to use the URI in `react-native-compressor`, it fails as if the video track was missing in the file.

The Signal iOS app works slightly differently. It does copy the video from the Photos library to a separate container in the Share Extension. But it applies the compression in the extension directly, and then share the compressed video with the app. Not sure why they do it like that, as it forces the user to wait for the compression to be completed before having a visual confirmation of the content to be shared.

I'm kind of stuck there at the moment, but I'll keep digging in the next few days.

**Comment by nomi9995** [comment]
@alariej can you make a GitHub repro of share extension and compressor? I will make a solution for you if you make a GitHub repro.

**Comment by alariej** [comment]
Hmmm, give me a few days. I don't promise but I'll see what I can do.

**Comment by alariej** [comment]
There might be a solution here: https://stackoverflow.com/a/57196411

It seems you need to enable "App Groups" in your Apple developer account, in order to be able to use Share Extensions. (I probably also did that, a few years ago).

**Comment by nomi9995** [comment]
@alariej i am using my office' app provioning profiles therefore, i have no access to add share group😔

**Comment by nomi9995** [comment]
@alariej I tested on the simulator and it is working well on my side.

**Comment by alariej** [comment]
@nomi9995 I suspect your test does not reproduce the case where a user makes a video with the phone's camera (it would then be a .mov file, and not a .mp4) and tries to load it into the app via a Share Extension. That's a problem with the simulator: It doesn't seem possible to simulate taking pictures or videos with the camera.

**Comment by alariej** [comment]
Submitted PR https://github.com/Shobbak/react-native-compressor/pull/98
