### ISSUE TITLE
backgroundUpload not working in foreground but only works when app is in background

### ISSUE THREAD

**Issue by ParthNandaniya** [Shobbak/react-native-compressor#97]
### Current behavior

When uploading video, it only uploads in background. when i try in foreground, it start uploading then restarts. basically it works in background but not in foreground. any solution to this ?

### Expected behavior
it should start/continue/complete upload in foreground and continue/complete in background

### Platform

- [X] iOS

### React Native Version
0.64.3

### React Native Compressor Version
^1.5.1

### Reproducible Steps And Demo

try uploading while app is in foreground and you will same o progress or restart process, when you let go app in background then it just works and completes upload

```
try {
        const uploadResult = await backgroundUpload(
          presignedUrl,
          eventData.uri,
          {
            httpMethod: 'PUT',
            headers: {
              'Content-Disposition': `filename="${eventData.fileType}.${fileType}"`,
              'Content-Type': `${eventData.fileType}/${fileType}`
            }
          },
          (written, total) => {
            console.log(written, total);
          }
        );

        if (uploadResult) {
          console.log('Completed!', uploadResult);
        }
      } catch (error) {
        console.log(`Error: `, error);
 }
```

let me know if there is a possible solution to this or in next update to resolve this.

Thanks

**Comment by nomi9995** [comment]
@ParthNandaniya is working for foreground on my side.  can you make a minimal repro if it reproduces on my side then I can fix it?

**Comment by ParthNandaniya** [comment]
@nomi9995 i'm not sure if i will get time to build separate repo, test and recreate it. let's see if anyone else report this issue. currently this featuer is not at highest priority so i can wait

**Comment by hkhan6916** [comment]
@nomi9995 have the same issue. Any update on this? When compressing, it fails as soon as the app is foregrounded on IOS. This is fine in android.
