### ISSUE TITLE
Could not find com.github.nomi9995:VideoCompressor:715bcc16e9.

### ISSUE THREAD

**Issue by lukeTheWizard** [Shobbak/react-native-compressor#99]
I cant build the app after npm install react-native-compressor@rnlessthan65. I have done a gradelw clean, removed node_modules and reinstalled.

### Current behavior
When running app with npx react-native run-android I get a build error of:
Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.nomi9995:VideoCompressor:715bcc16e9.
     Searched in the following locations: .........
### Expected behavior
App Builds
### Platform

- [X] Android
- [] iOS

### React Native Version
0.60.4

**Comment by nomi9995** [comment]
@lukeTheWizard can you add this line into `build.gradle` > `allprojects` > `repositories` and test again.
```
maven { url 'https://jitpack.io' }
```

**Comment by lukeTheWizard** [comment]
@nomi9995 that fixes the compilation issues. However Im now getting a runtime error:

error: bundling failed: SyntaxError: /REDACTED/node_modules/react-native-compressor/src/Audio/index.tsx: Unexpected token, expected ")" (62:18)

  60 |         });
  61 |       }
> 62 |     } catch (error: any) {
     |                   ^
  63 |       throw error.message;
  64 |     }
  65 |   },

**Comment by nomi9995** [comment]
@lukeTheWizard are you trying to compress audio?

**Comment by lukeTheWizard** [comment]
No just a regular image. The error pops up from just importing. Could this be a node version or something? My project isn't typescript either

**Comment by nomi9995** [comment]
@lukeTheWizard which version of node, you are using?
